### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by Ken-B** [jlapeyre/SJulia#1]
Before looking at the code, it would be nice to know which license you plan to use.

A lot of julia packages (http://pkg.julialang.org/) are released under the permissive MIT license, but you are of course free to choose yourself.

**Comment by jlapeyre** [comment]
Right, I keep forgetting the license file. I am using the standard Julia license.

**Comment by Ken-B** [comment]
Do you mean the MIT license? 

The convention is to put a `LICENSE.md` file in the main directory. See for a random example:https://github.com/JuliaLang/Graphs.jl/blob/master/LICENSE.md

By the way, the license file gets made automatically when you create a new package using `Pkg.generate("FooBar","MIT")`, as explained in the [documentation](http://julia.readthedocs.org/en/latest/manual/packages/#generating-a-new-package).

**Comment by jlapeyre** [comment]
Sorry, I forgot to add that I was pushing the license. It is done. I usually use Pkg.generate(), but I wasn't thinking about a standard package with Modules when I began the project. It's still to early for that. But, thanks for reminding me about the license!
